# Generated by Django 4.1.1 on 2022-10-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, unique=True)),
                ('api_host', models.CharField(max_length=100)),
                ('api_protocol', models.PositiveSmallIntegerField(choices=[(1, 'http'), (2, 'https')], default=2)),
                ('api_port', models.IntegerField(default=80)),
                ('api_label', models.CharField(max_length=250)),
                ('api_page_size', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='NdrCoreDataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_url', models.URLField()),
                ('schema_label', models.CharField(max_length=100)),
                ('schema_name', models.CharField(max_length=100)),
                ('fixture_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NdrCorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(help_text='The name of the view to display', max_length=200)),
                ('name', models.CharField(help_text="The name of the page, e.g. the page's title", max_length=200)),
                ('label', models.CharField(help_text="The label of the page, e.g. the page's navigation label", max_length=200)),
                ('nav_icon', models.CharField(blank=True, help_text='The fontawesome nav icon (leave blank if none)', max_length=200)),
                ('index', models.IntegerField(default=0, help_text='Page order')),
            ],
        ),
        migrations.CreateModel(
            name='NdrCoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=100, unique=True)),
                ('value_label', models.CharField(max_length=100)),
                ('value_help_text', models.CharField(max_length=250)),
                ('value_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NdrSearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('field_type', models.PositiveSmallIntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Dictionary')], default=1)),
                ('field_required', models.BooleanField(default=False)),
                ('help_text', models.CharField(max_length=250)),
                ('api_parameter', models.CharField(max_length=100)),
                ('schema_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchFieldFormConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_row', models.IntegerField()),
                ('field_column', models.IntegerField()),
                ('field_size', models.IntegerField()),
                ('search_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndr_core.ndrsearchfield')),
            ],
        ),
        migrations.CreateModel(
            name='SearchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndr_core.apiconfiguration')),
                ('search_form_fields', models.ManyToManyField(to='ndr_core.searchfieldformconfiguration')),
            ],
        ),
    ]
