# Generated by Django 4.1.2 on 2022-10-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterablelistconfiguration',
            name='list_name',
            field=models.CharField(default='name', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchconfiguration',
            name='conf_name',
            field=models.CharField(default='name', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
