# Generated by Django 4.1.3 on 2022-12-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreimage',
            name='citation',
            field=models.CharField(blank=True, default='', help_text='Citation text of the image.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcoreimage',
            name='caption',
            field=models.CharField(blank=True, default='', help_text='Caption of the image.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcoreimage',
            name='image_group',
            field=models.CharField(choices=[('backgrounds', 'Background Images'), ('elements', 'Element Images'), ('figures', 'Figures'), ('logos', 'Logos'), ('people', 'People')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ndrcoreimage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title of the image.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcoreimage',
            name='url',
            field=models.URLField(blank=True, default=None, help_text='URL to image or source', null=True),
        ),
    ]
