# Generated by Django 4.2.6 on 2023-10-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ndrcoresearchconfiguration",
            name="api_connection_url",
            field=models.CharField(
                help_text="Connection URL for the API endpoint.",
                max_length=512,
                verbose_name="Connection URL",
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchconfiguration",
            name="conf_label",
            field=models.CharField(
                help_text="Label of this search configuration",
                max_length=100,
                unique=True,
                verbose_name="Configuration Label",
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchconfiguration",
            name="conf_name",
            field=models.CharField(
                help_text="Name of this search configuration. Can't contain spaces or special characters.",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Configuration Name",
            ),
        ),
    ]
