# Generated by Django 4.1.3 on 2022-11-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdrCoreResultTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_field_name', models.CharField(max_length=100)),
                ('source_field_name', models.CharField(max_length=100)),
                ('alternate_field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('field_none_value', models.CharField(default='', max_length=100)),
                ('field_label', models.CharField(blank=True, max_length=100, null=True)),
                ('field_container', models.CharField(max_length=100)),
                ('field_renderer', models.IntegerField(blank=True, choices=[(1, 'geonames.org')], null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndr_core.ndrcoreapiconfiguration')),
            ],
        ),
    ]
