# Generated by Django 4.1.1 on 2022-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorepage',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Template Page'), (2, 'Simple Search'), (3, 'Custom Search'), (4, 'Contact Form'), (5, 'Filterable List')], default=1),
        ),
        migrations.AlterField(
            model_name='ndrcorepage',
            name='view_name',
            field=models.CharField(help_text='The url part of your page (e.g. https://yourdomain.org/p/view_name)', max_length=200),
        ),
    ]
