# Generated by Django 4.1.3 on 2022-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreapiimplementation',
            name='description',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='ndrcoreapiimplementation',
            name='label',
            field=models.CharField(default='Label', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndrcoreapiimplementation',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='ndrcoreapiimplementation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
