# Generated by Django 4.1.2 on 2022-10-18 05:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcorepage',
            name='template_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Text for your template page', null=True),
        ),
    ]
