# Generated by Django 4.1.4 on 2022-12-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ndrcoreimage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ndrcoreimage',
            name='image_group',
            field=models.CharField(choices=[('backgrounds', 'Background Images'), ('elements', 'Element Images'), ('figures', 'Figures'), ('logos', 'Partner Logos'), ('people', 'People')], max_length=100),
        ),
    ]
