# Generated by Django 4.1.1 on 2022-09-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, unique=True)),
                ('api_host', models.CharField(max_length=100)),
                ('api_protocol', models.PositiveSmallIntegerField(choices=[(1, 'HTTP'), (2, 'HTTPS')], default=2)),
                ('api_port', models.IntegerField(default=80)),
                ('api_label', models.CharField(max_length=250)),
                ('api_page_size', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='SearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('field_type', models.PositiveSmallIntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Dictionary')], default=1)),
                ('field_required', models.BooleanField(default=False)),
                ('help_text', models.CharField(max_length=250)),
                ('api_parameter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchFieldFormConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_row', models.IntegerField()),
                ('field_column', models.IntegerField()),
                ('field_size', models.IntegerField()),
                ('search_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndr_core.searchfield')),
            ],
        ),
        migrations.CreateModel(
            name='SearchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndr_core.apiconfiguration')),
                ('search_form_fields', models.ManyToManyField(to='ndr_core.searchfieldformconfiguration')),
            ],
        ),
    ]
