# pylint: skip-file
# Generated by Django 4.2.7 on 2023-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ndrcoreuielement",
            name="link_element",
        ),
        migrations.RemoveField(
            model_name="ndrcoreuielement",
            name="show_image",
        ),
        migrations.RemoveField(
            model_name="ndrcoreuielement",
            name="show_text",
        ),
        migrations.RemoveField(
            model_name="ndrcoreuielement",
            name="show_title",
        ),
        migrations.AlterField(
            model_name="ndrcoreuielement",
            name="show_indicators",
            field=models.BooleanField(
                default=False,
                help_text="Show the indicators for slideshows and carousels?",
            ),
        ),
    ]
