# Generated by Django 4.1.3 on 2022-11-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0002_ndrcoreresulttemplatefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.CharField(max_length=200)),
                ('message_text', models.TextField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_ret_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='ndrcoreapiconfiguration',
            name='api_port',
            field=models.IntegerField(default=80, help_text='Port to connect to.'),
        ),
        migrations.AlterField(
            model_name='ndrcoreapiconfiguration',
            name='api_url_stub',
            field=models.CharField(blank=True, default=None, help_text='Static URL part after host, before API parameters.', max_length=50, null=True),
        ),
    ]
