# pylint: skip-file
# Generated by Django 4.2.7 on 2023-11-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0002_remove_ndrcoreuielement_link_element_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcorepage",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ndrcorepage",
            name="page_type",
            field=models.IntegerField(
                choices=[
                    (1, "Template Page"),
                    (3, "Search Page"),
                    (5, "Contact Form"),
                    (7, "Flip Book"),
                    (8, "About Us Page"),
                ],
                default=1,
                help_text="Choose a type for your page.",
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorerichtexttranslation",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("NdrCoreSearchField", "Search Field Table"),
                    ("NdrCoreResultField", "Result Field Table"),
                    ("NdrCorePage", "Page Table"),
                    ("NdrCoreValue", "Settings Table"),
                    ("NdrCoreSearchConfiguration", "Search Configuration Table"),
                    ("NdrCoreImage", "Image Table"),
                    ("NdrCoreUiElementItem", "UI Element Table"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoretranslation",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("NdrCoreSearchField", "Search Field Table"),
                    ("NdrCoreResultField", "Result Field Table"),
                    ("NdrCorePage", "Page Table"),
                    ("NdrCoreValue", "Settings Table"),
                    ("NdrCoreSearchConfiguration", "Search Configuration Table"),
                    ("NdrCoreImage", "Image Table"),
                    ("NdrCoreUiElementItem", "UI Element Table"),
                ],
                max_length=100,
            ),
        ),
    ]
