# Generated by Django 4.1.3 on 2022-12-03 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0002_ndrcorevalue_is_user_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcorevalue',
            name='is_user_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ndrcorevalue',
            name='value_help_text',
            field=models.CharField(help_text='This is the help text of the form field.', max_length=250),
        ),
        migrations.AlterField(
            model_name='ndrcorevalue',
            name='value_label',
            field=models.CharField(help_text='This is a human readable label for the value. It is used in the admin view forms.', max_length=100),
        ),
        migrations.AlterField(
            model_name='ndrcorevalue',
            name='value_name',
            field=models.CharField(help_text="This is the identifier of a NdrCoreValue. Can't contain special characters.", max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ndrcorevalue',
            name='value_value',
            field=models.CharField(help_text='This is the actual value which can be updated', max_length=100),
        ),
        migrations.CreateModel(
            name='NdrCoreSearchStatisticEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=100)),
                ('search_time', models.DateTimeField()),
                ('search_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndr_core.ndrcoreapiconfiguration')),
            ],
        ),
    ]
