# Generated by Django 4.1.1 on 2022-10-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0002_ndrcorepage_page_type_alter_ndrcorepage_view_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcorepage',
            name='view_name',
            field=models.CharField(help_text='The url part of your page (e.g. https://yourdomain.org/p/view_name)', max_length=200, unique=True),
        ),
    ]
