# Generated by Django 4.1.2 on 2022-10-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0002_filterablelistconfiguration_list_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrsearchfield',
            name='field_name',
            field=models.CharField(help_text="Choose a name for the field. Can't contain spaces or special charactersand must be unique", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='searchfieldformconfiguration',
            name='field_column',
            field=models.IntegerField(help_text='The column in the form. Is a value between 1 and 12.'),
        ),
        migrations.AlterField(
            model_name='searchfieldformconfiguration',
            name='field_row',
            field=models.IntegerField(help_text='The row in the form. Starts with 1.'),
        ),
        migrations.AlterField(
            model_name='searchfieldformconfiguration',
            name='field_size',
            field=models.IntegerField(help_text='The size of the field. Is a value between 1 and 12.'),
        ),
        migrations.AlterField(
            model_name='searchfieldformconfiguration',
            name='search_field',
            field=models.ForeignKey(help_text='The search field to place in a form', on_delete=django.db.models.deletion.CASCADE, to='ndr_core.ndrsearchfield'),
        ),
    ]
