# Generated by Django 4.1.3 on 2022-12-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0002_ndrcoreimage_citation_alter_ndrcoreimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorevalue',
            name='value_options',
            field=models.CharField(default='', help_text='Used for value_type LIST: comma-separated list', max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcorevalue',
            name='value_type',
            field=models.IntegerField(choices=[(1, 'String'), (2, 'Integer'), (3, 'Boolean'), (4, 'List')], default=1, help_text='The type of your value'),
        ),
    ]
