# pylint: skip-file
# Generated by Django 4.2.7 on 2023-11-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0003_ndrcorepage_last_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcoreuielementitem",
            name="manifest_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ndr_core.ndrcoremanifestgroup",
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoreuielement",
            name="type",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("slides", "Slideshow"),
                    ("carousel", "Carousel"),
                    ("jumbotron", "Jumbotron"),
                    ("iframe", "IFrame"),
                    ("banner", "Banner"),
                    ("manifest_viewer", "Manifest Viewer"),
                ],
                help_text="Type of the element. Decides how it is rendered. ",
                max_length=100,
            ),
        ),
    ]
