# Generated by Django 4.1.2 on 2022-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0003_ndrcorecolorscheme_ndrcoreuistyle_ndrcorrection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreuistyle',
            name='label',
            field=models.CharField(default='Label', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ndrcoreuistyle',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
