# Generated by Django 4.1.3 on 2022-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0003_usermessage_alter_ndrcoreapiconfiguration_api_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreapiconfiguration',
            name='api_description',
            field=models.TextField(default=''),
        ),
    ]
