# Generated by Django 4.1.2 on 2022-10-11 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0003_alter_ndrsearchfield_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfieldformconfiguration',
            name='field_column',
            field=models.IntegerField(help_text='The column in the form. Is a value between 1 and 12.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='searchfieldformconfiguration',
            name='field_size',
            field=models.IntegerField(help_text='The size of the field. Is a value between 1 and 12.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
