# Generated by Django 4.1.3 on 2022-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0003_ndrcorevalue_value_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreusermessage',
            name='message_archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndrcoreusermessage',
            name='message_forwarded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
