# Generated by Django 4.1.7 on 2023-03-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0003_ndrcoresearchstatisticentry_search_no_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoresearchfield',
            name='list_choices',
            field=models.TextField(blank=True, default='', help_text='Comma separated list of choices for dropdowns'),
        ),
        migrations.AlterField(
            model_name='ndrcoresearchfield',
            name='field_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Dropdown List'), (4, 'Multi Select List'), (5, 'Boolean'), (6, 'Date'), (7, 'Date Range'), (8, 'Hidden')], default=1, help_text='Type of the form field. String produces a text field, Number a number field and dictionary a dropdown.'),
        ),
    ]
