# Generated by Django 4.1.2 on 2022-10-14 10:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0004_alter_searchfieldformconfiguration_field_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorepage',
            name='template_text',
            field=ckeditor.fields.RichTextField(help_text='Text for your template page', null=True),
        ),
        migrations.AlterField(
            model_name='ndrcorepage',
            name='name',
            field=models.CharField(help_text="The name of the page, e.g. the page's title", max_length=200, verbose_name='Page Title'),
        ),
        migrations.AlterField(
            model_name='searchconfiguration',
            name='api_configuration',
            field=models.ForeignKey(help_text='The API to query', on_delete=django.db.models.deletion.CASCADE, to='ndr_core.apiconfiguration'),
        ),
        migrations.AlterField(
            model_name='searchconfiguration',
            name='conf_name',
            field=models.CharField(help_text='Name of this search configuration', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='searchconfiguration',
            name='search_form_fields',
            field=models.ManyToManyField(help_text='Fields associated with this configuration', to='ndr_core.searchfieldformconfiguration'),
        ),
    ]
