# pylint: skip-file
# Generated by Django 4.2.7 on 2023-11-18 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0004_ndrcoreuielementitem_manifest_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ndrcoreresultfieldcardconfiguration",
            name="field_column",
            field=models.IntegerField(
                help_text="The column in the card. Is a value between 1 and 12.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoreresultfieldcardconfiguration",
            name="field_row",
            field=models.IntegerField(
                help_text="The row in the card. Starts with 1.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoreresultfieldcardconfiguration",
            name="field_size",
            field=models.IntegerField(
                help_text="The size of the field. Is a value between 1 and 12.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
