# Generated by Django 4.1.2 on 2022-11-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0004_ndrcoreuistyle_label_alter_ndrcoreuistyle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='scheme_label',
            field=models.CharField(default='Label', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ndrcorecolorscheme',
            name='scheme_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
