# Generated by Django 4.1.3 on 2022-12-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0004_ndrcoreusermessage_message_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndrcoreuielement',
            name='element_type',
        ),
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='autoplay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='link_element',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='show_indicators',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='show_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='type',
            field=models.CharField(choices=[('CARD', 'Card'), ('slides', 'Slideshow'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron')], default='CARD', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ndrcoreusermessage',
            name='message_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ndrcoreusermessage',
            name='message_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NdrCoreUiElementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_idx', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndr_core.ndrcoreuielement')),
                ('ndr_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndr_core.ndrcoreimage')),
            ],
        ),
    ]
