# Generated by Django 4.1.7 on 2023-04-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0005_ndrcoreupload_alter_ndrcoreuielement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreapiconfiguration',
            name='api_repository_url',
            field=models.URLField(blank=True, default=None, help_text='URL to the data repository where this data is stored.', null=True, verbose_name='Repository URL'),
        ),
        migrations.AlterField(
            model_name='ndrcoresearchfield',
            name='field_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Dropdown List'), (4, 'Multi Select List'), (5, 'Boolean'), (6, 'Date'), (7, 'Date Range'), (8, 'Number Range'), (9, 'Hidden')], default=1, help_text='Type of the form field. String produces a text field, Number a number field and dictionary a dropdown.'),
        ),
    ]
