# Generated by Django 4.1.3 on 2022-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0005_remove_ndrcoreuielement_element_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='title',
            field=models.CharField(default='', help_text='Title of the element for your reference.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='use_image_conf',
            field=models.BooleanField(default=True, help_text="Use the image's title, caption and URL?"),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='autoplay',
            field=models.BooleanField(default=False, help_text='Autoplay carousels and slideshows?'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='link_element',
            field=models.BooleanField(default=True, help_text='Link the elements to the supplied url?'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='show_image',
            field=models.BooleanField(default=True, help_text='Show the images?'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='show_indicators',
            field=models.BooleanField(default=True, help_text='Show the indicators for slideshows and carousels?'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='show_text',
            field=models.BooleanField(default=True, help_text="Show the element's text?"),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Show the title?'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slides', 'Slideshow'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron')], max_length=100),
        ),
    ]
