# Generated by Django 4.1.2 on 2022-11-20 19:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0005_ndrcorecolorscheme_scheme_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='button_border_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='second_button_border_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
