# Generated by Django 4.1.7 on 2023-04-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0006_ndrcoreapiconfiguration_api_repository_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoresearchfield',
            name='lower_value',
            field=models.IntegerField(help_text='The lower value of a range field', null=True),
        ),
        migrations.AddField(
            model_name='ndrcoresearchfield',
            name='upper_value',
            field=models.IntegerField(help_text='The upper value of a range field', null=True),
        ),
        migrations.AlterField(
            model_name='ndrcoresearchfield',
            name='field_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Dropdown List'), (4, 'Multi Select List'), (5, 'Boolean'), (6, 'Date'), (7, 'Date Range'), (8, 'Number Range'), (9, 'Hidden'), (10, 'Info Text')], default=1, help_text='Type of the form field. String produces a text field, Number a number field and dictionary a dropdown.'),
        ),
    ]
