# Generated by Django 4.1.3 on 2022-12-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0006_ndrcoreuielement_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcorepage',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Template Page'), (2, 'Simple Search'), (3, 'Custom Search'), (4, 'Simple/Custom Search'), (5, 'Contact Form'), (6, 'Filterable List'), (7, 'Flip Book'), (8, 'About Us Page')], default=1, help_text='Choose a type for your page. Template is a static page, search pagesdisplay search forms, a filtered list displays data resources with afilter, contact form displays a form to send a message.'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielementitem',
            name='ndr_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ndr_core.ndrcoreimage'),
        ),
    ]
