# Generated by Django 4.2.7 on 2023-12-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0006_ndrcoreresultfield_field_classes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ndrcoreresultfield",
            name="display_border",
        ),
        migrations.RemoveField(
            model_name="ndrcoreresultfield",
            name="expression",
        ),
        migrations.RemoveField(
            model_name="ndrcoreresultfield",
            name="field_filter",
        ),
        migrations.RemoveField(
            model_name="ndrcoreresultfield",
            name="field_type",
        ),
        migrations.RemoveField(
            model_name="ndrcoreresultfield",
            name="html_display",
        ),
        migrations.RemoveField(
            model_name="ndrcoreresultfield",
            name="md_display",
        ),
        migrations.AlterField(
            model_name="ndrcorerichtexttranslation",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("ndrcoresearchfield", "Search Field Table"),
                    ("ndrcoreresultfield", "Result Field Table"),
                    ("ndrcorepage", "Page Table"),
                    ("ndrcorevalue", "Settings Table"),
                    ("ndrcoresearchconfiguration", "Search Configuration Table"),
                    ("ndrcoreimage", "Image Table"),
                    ("ndrcoreuielementitem", "UI Element Table"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoretranslation",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("ndrcoresearchfield", "Search Field Table"),
                    ("ndrcoreresultfield", "Result Field Table"),
                    ("ndrcorepage", "Page Table"),
                    ("ndrcorevalue", "Settings Table"),
                    ("ndrcoresearchconfiguration", "Search Configuration Table"),
                    ("ndrcoreimage", "Image Table"),
                    ("ndrcoreuielementitem", "UI Element Table"),
                ],
                max_length=100,
            ),
        ),
    ]
