# Generated by Django 4.1.2 on 2022-11-20 19:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0006_ndrcorecolorscheme_button_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='error_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='success_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
