# Generated by Django 4.2.7 on 2023-12-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0007_remove_ndrcoreresultfield_display_border_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcoreresultfield",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The label of the result field",
                max_length=100,
            ),
        ),
    ]
