# Generated by Django 4.1.7 on 2023-04-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0007_ndrcoresearchfield_lower_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoresearchfield',
            name='use_in_csv_export',
            field=models.BooleanField(default=False, help_text='Should this field be included in the CSV export?'),
        ),
    ]
