# Generated by Django 4.1.3 on 2022-12-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0007_alter_ndrcorepage_page_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorepage',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='ndr_core.ndrcorepage'),
        ),
    ]
