# Generated by Django 4.1.2 on 2022-11-21 14:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0008_ndrcorecolorscheme_button_hover_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorecolorscheme',
            name='info_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
