# Generated by Django 4.2.7 on 2023-12-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0008_ndrcoreresultfield_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcoresearchconfiguration",
            name="citation_expression",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Expression to generate a citation for a result.",
                max_length=512,
                null=True,
                verbose_name="Citation Expression",
            ),
        ),
    ]
