# Generated by Django 4.2 on 2023-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0009_ndrcoresearchconfiguration_search_has_compact_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdrCoreTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('table_name', models.CharField(choices=[('NdrCoreSearchField', 'Search Field Table'), ('NdrCorePage', 'Page Table')], max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ndrcorevalue',
            name='value_options',
            field=models.CharField(default='', help_text='Used for value_type LIST and MULTI_LIST: comma-separated list', max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcorevalue',
            name='value_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('list', 'List'), ('url', 'URL'), ('multi_list', 'Multi List')], default='string', help_text='The type of your value', max_length=10),
        ),
    ]
