# Generated by Django 4.2 on 2023-08-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0010_ndrcoretranslation_alter_ndrcorevalue_value_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoretranslation',
            name='object_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
