# Generated by Django 4.2.7 on 2024-01-12 15:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0011_ndrcorecolorscheme_nav_active_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcorecolorscheme",
            name="footer_link_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="ndrcorecolorscheme",
            name="footer_link_hover_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="ndrcorecolorscheme",
            name="powered_by_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
