# Generated by Django 4.2 on 2023-08-29 13:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0011_ndrcoretranslation_object_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NdrCoreRichTextTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                (
                    "table_name",
                    models.CharField(
                        choices=[
                            ("NdrCoreSearchField", "Search Field Table"),
                            ("NdrCorePage", "Page Table"),
                        ],
                        max_length=100,
                    ),
                ),
                ("object_id", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                (
                    "translation",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Text for your template page", null=True
                    ),
                ),
            ],
        ),
    ]
