# Generated by Django 5.0.2 on 2024-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0011_ndrcorecolorscheme_footer_link_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcoresearchconfiguration",
            name="manifest_relation_expression",
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
