# Generated by Django 4.2 on 2023-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0012_ndrcorerichtexttranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcoreimage",
            name="language",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ndrcoreimage",
            name="image_group",
            field=models.CharField(
                choices=[
                    ("page_logos", "Page Logos"),
                    ("backgrounds", "Background Images"),
                    ("elements", "Slideshow Images"),
                    ("figures", "Figures"),
                    ("logos", "Partner Images"),
                    ("people", "People"),
                ],
                max_length=100,
            ),
        ),
    ]
