# Generated by Django 4.2.7 on 2024-01-12 15:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0012_ndrcorecolorscheme_footer_link_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcorecolorscheme",
            name="tab_active_title_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Color for active tab titles.",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="ndrcorecolorscheme",
            name="tab_title_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Color for tab titles.",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
    ]
