# Generated by Django 5.0.2 on 2024-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0012_ndrcoresearchconfiguration_manifest_relation_expression"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ndrcoremanifest",
            name="id",
        ),
        migrations.AddField(
            model_name="ndrcoremanifest",
            name="identifier",
            field=models.CharField(
                default="na",
                help_text="Identifier of the manifest. Is used to reference the manifest in the code.",
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
    ]
