# Generated by Django 4.2 on 2023-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0013_ndrcoreimage_language_alter_ndrcoreimage_image_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcorevalue",
            name="is_translatable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ndrcoreimage",
            name="image_group",
            field=models.CharField(
                choices=[
                    ("page_logos", "Page Logos"),
                    ("backgrounds", "Background Images"),
                    ("elements", "Slideshow Images"),
                    ("figures", "Figures"),
                    ("logos", "Partner Images"),
                    ("people", "People"),
                ],
                help_text="Group the image belongs to.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoreimage",
            name="language",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Language of the image.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorerichtexttranslation",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("NdrCoreSearchField", "Search Field Table"),
                    ("NdrCorePage", "Page Table"),
                    ("NdrCoreValue", "Settings Table"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoretranslation",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("NdrCoreSearchField", "Search Field Table"),
                    ("NdrCorePage", "Page Table"),
                    ("NdrCoreValue", "Settings Table"),
                ],
                max_length=100,
            ),
        ),
    ]
