# Generated by Django 4.2 on 2023-08-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0014_ndrcorevalue_is_translatable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcorepage",
            name="show_page_title",
            field=models.BooleanField(
                default=True, help_text="Should the page title be displayed?"
            ),
        ),
    ]
