# Generated by Django 5.0.4 on 2024-04-08 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0013_ndrcorecolorscheme_tab_active_title_color_and_more"),
        ("ndr_core", "0014_ndrcoresearchconfiguration_manifest_page_expression"),
    ]

    operations = []
