# Generated by Django 5.0.4 on 2024-04-08 15:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0015_merge_20240408_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcoresearchfield",
            name="list_condition",
            field=models.CharField(
                blank=True,
                choices=[("OR", "OR"), ("AND", "AND")],
                default="OR",
                help_text="Condition for multiple list values",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorecolorscheme",
            name="footer_link_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorecolorscheme",
            name="footer_link_hover_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorecolorscheme",
            name="nav_active_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Color for active navigation links.",
                image_field=None,
                max_length=18,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorecolorscheme",
            name="nav_link_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Color navigation for links.",
                image_field=None,
                max_length=18,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorecolorscheme",
            name="powered_by_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorecolorscheme",
            name="tab_active_title_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Color for active tab titles.",
                image_field=None,
                max_length=18,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorecolorscheme",
            name="tab_title_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Color for tab titles.",
                image_field=None,
                max_length=18,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchconfiguration",
            name="manifest_page_expression",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Expression to generate a link to a page in a manifest.",
                max_length=512,
                null=True,
                verbose_name="Manifest Page Expression",
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchconfiguration",
            name="manifest_relation_expression",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Expression to generate a relation to a manifest for a result.",
                max_length=512,
                null=True,
                verbose_name="Manifest Relation Expression",
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="field_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "String"),
                    (2, "Number"),
                    (3, "Dropdown List"),
                    (4, "Multi Select List"),
                    (5, "Boolean"),
                    (6, "Date"),
                    (7, "Date Range"),
                    (8, "Number Range"),
                    (9, "Hidden"),
                    (10, "Info Text"),
                    (11, "Boolean List"),
                ],
                default=1,
                help_text="Type of the form field. String produces a text field, Number a number field and dictionary a dropdown.",
            ),
        ),
    ]
