# Generated by Django 4.2 on 2023-09-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0016_ndrcorepage_show_in_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcoresearchfield",
            name="initial_value",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Initial value of the field",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="ndrcoresearchstatisticentry",
            name="language",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Language of the search.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcorerichtexttranslation",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("NdrCoreSearchField", "Search Field Table"),
                    ("NdrCorePage", "Page Table"),
                    ("NdrCoreValue", "Settings Table"),
                    ("NdrCoreSearchConfiguration", "Search Configuration Table"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoretranslation",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("NdrCoreSearchField", "Search Field Table"),
                    ("NdrCorePage", "Page Table"),
                    ("NdrCoreValue", "Settings Table"),
                    ("NdrCoreSearchConfiguration", "Search Configuration Table"),
                ],
                max_length=100,
            ),
        ),
    ]
