# Generated by Django 5.0.4 on 2024-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0016_ndrcoresearchfield_list_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="field_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (None, "Select a Type"),
                    (1, "String"),
                    (2, "Number"),
                    (3, "Dropdown List"),
                    (4, "Multi Select List"),
                    (5, "Boolean"),
                    (6, "Date"),
                    (7, "Date Range"),
                    (8, "Number Range"),
                    (9, "Hidden"),
                    (10, "Info Text"),
                    (11, "Boolean List"),
                ],
                help_text="Type of the form field. String produces a text field, Number a number field and dictionary a dropdown.",
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="list_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OR", "OR - Either in the selection"),
                    ("AND", "AND - All in the selection"),
                    ("CHOOSE", "CHOOSE - Let the user decide"),
                ],
                default="OR",
                help_text="Condition for multiple list values",
                max_length=10,
            ),
        ),
    ]
