# Generated by Django 4.2 on 2023-09-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0017_ndrcoresearchfield_initial_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NdrCoreManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title of the manifest. Is shown in the dropdown of the page.",
                        max_length=200,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/manifests/")),
            ],
        ),
        migrations.AlterField(
            model_name="ndrcorepage",
            name="page_type",
            field=models.IntegerField(
                choices=[
                    (1, "Template Page"),
                    (2, "Simple Search"),
                    (3, "Custom Search"),
                    (4, "Simple/Custom Search"),
                    (5, "Contact Form"),
                    (6, "Filterable List"),
                    (7, "Flip Book"),
                    (8, "About Us Page"),
                    (9, "Viewer Page"),
                ],
                default=1,
                help_text="Choose a type for your page.",
            ),
        ),
    ]
