# Generated by Django 5.0.4 on 2024-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0017_alter_ndrcoresearchfield_field_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="api_parameter",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name of the API parameter which is used to generate a query. If empty, the field_name is used.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="data_field_type",
            field=models.CharField(
                blank=True,
                choices=[("int", "Integer"), ("string", "String")],
                default="",
                help_text="Type of the field in the data source. This may change the way data is queried.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="field_label",
            field=models.CharField(
                help_text="This is the form field's label. It is shown to the user. This value is translatable.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="field_name",
            field=models.CharField(
                help_text="Choose a name for the field. Can't contain spaces or special charactersand must be unique in your installation. Keep it short.",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="initial_value",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Initial value of the field. Refer to info box for valid values.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ndrcoresearchfield",
            name="input_transformation_regex",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Regex to transform the input value before sending it to the API. {_value_} inserts the value.<br/> (Example to convert a year to a date regex: '{_value_}-??-??')",
                max_length=100,
            ),
        ),
    ]
