# Generated by Django 4.2 on 2023-09-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0018_ndrcoremanifest_alter_ndrcorepage_page_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndrcoresearchfield",
            name="data_field_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of the field in the data source. This may change the way data is queried.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="ndrcoresearchfield",
            name="input_transformation_regex",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Regex to transform the input value before sending it to the API.",
                max_length=100,
            ),
        ),
    ]
