# Generated by Django 4.2 on 2023-09-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ndr_core", "0019_ndrcoresearchfield_data_field_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NdrCoreManifestGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "order_value_1_title",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "order_value_2_title",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "order_value_3_title",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ndrcoremanifest",
            name="order_value_1",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ndrcoremanifest",
            name="order_value_2",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ndrcoremanifest",
            name="order_value_3",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ndrcoremanifest",
            name="manifest_group",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="ndr_core.ndrcoremanifestgroup",
            ),
            preserve_default=False,
        ),
    ]
