# Generated by Django 5.0.4 on 2026-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0042_remove_ndrcoreresultfieldcardconfiguration_tab_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreuielementitem',
            name='js_module_config',
            field=models.JSONField(blank=True, default=dict, help_text='Module configuration (auto-populated from package or manual)'),
        ),
        migrations.AddField(
            model_name='ndrcoreuielementitem',
            name='js_module_extracted',
            field=models.BooleanField(default=False, help_text='Whether the package has been extracted'),
        ),
        migrations.AddField(
            model_name='ndrcoreuielementitem',
            name='js_module_name',
            field=models.CharField(blank=True, default='', help_text='JavaScript module identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='ndrcoreuielementitem',
            name='js_module_package',
            field=models.FileField(blank=True, help_text='Uploaded module package (zip file with static/ and media/ folders)', null=True, upload_to='js_modules/packages/'),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slides', 'Slideshow'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron'), ('iframe', 'IFrame'), ('banner', 'Banner'), ('manifest_viewer', 'Manifest Viewer'), ('data_object', 'Data Object'), ('video', 'Video'), ('audio', 'Audio Player'), ('academic_about', 'About Me'), ('team_grid', 'Team Members Grid'), ('js_module', 'JavaScript Module')], help_text='Type of the element. Decides how it is rendered. ', max_length=100),
        ),
    ]
