# Generated by Django 6.0.3 on 2026-03-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0044_remove_ndrcoreuielementitem_js_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcorepage',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Template Page'), (3, 'Search Page'), (4, 'Data List Page'), (5, 'Contact Form'), (7, 'Flip Book'), (8, 'About Us Page'), (9, 'Full Screen Page')], default=1, help_text='Choose a type for your page.'),
        ),
        migrations.AlterField(
            model_name='ndrcorepage',
            name='view_name',
            field=models.CharField(help_text='The url part of your page (e.g. https://yourdomain.org/p/view_name)', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='ndrcorepage',
            unique_together={('parent_page', 'view_name')},
        ),
    ]
