# Generated by Django 6.0.3 on 2026-03-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0045_page_view_name_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slides', 'Slideshow'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron'), ('iframe', 'IFrame'), ('banner', 'Banner'), ('manifest_viewer', 'Manifest Viewer'), ('data_object', 'Data Object'), ('video', 'Video'), ('audio', 'Audio Player'), ('academic_about', 'About Me'), ('team_grid', 'Team Members Grid'), ('js_module', 'JavaScript Module'), ('card_grid', 'Card Grid')], help_text='Type of the element. Decides how it is rendered. ', max_length=100),
        ),
    ]
