# Generated by Django 6.0.3 on 2026-05-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0049_alter_ndrcoreuielement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcoresearchconfiguration',
            name='simple_query_main_field',
            field=models.CharField(default='transcription.original', help_text='The main field to query for a simple search.', max_length=500),
        ),
    ]
