# Generated by Django 6.0.3 on 2026-06-15 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0057_ndrcoresearchconfiguration_show_and_or_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcorepage',
            name='overlay_color_dark',
            field=models.CharField(blank=True, default=None, help_text='Overlay colour for dark mode (leave blank to use same as light mode)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='ndrcorepage',
            name='overlay_opacity_dark',
            field=models.FloatField(blank=True, default=None, help_text='Overlay opacity for dark mode (leave blank to use same as light mode)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='ndrcoreuielement',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slides', 'Slideshow'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron'), ('iframe', 'IFrame'), ('banner', 'Banner'), ('manifest_viewer', 'Manifest Viewer'), ('data_object', 'Data Object'), ('video', 'Video'), ('audio', 'Audio Player'), ('academic_about', 'About Me'), ('team_grid', 'Team Members Grid'), ('js_module', 'JavaScript Module'), ('card_grid', 'Card Grid'), ('pdf_viewer', 'PDF Viewer'), ('zotero_group', 'Zotero Group Library')], help_text='Type of the element. Decides how it is rendered. ', max_length=100),
        ),
    ]
