# Generated by Django 6.0.3 on 2026-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core', '0058_overlay_color_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndrcoreuielement',
            name='card_width',
            field=models.CharField(blank=True, default='18rem', help_text='CSS width of the card (e.g. 18rem, 300px, 100%). Applies only to single Card elements.', max_length=30),
        ),
    ]
